### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by thinkspill** [thephpleague/booboo#36]
Hi! I'm curious if there's any info about when PHP 7 support might be arriving?

**Comment by brandonsavage** [comment]
PHP 7 is supported in Master, and will be supported in 2.0. PHP 7 will be the exclusively supported platform in v3.0.

**Comment by jblotus** [comment]
are there any gotchas / known issues using master with php 7? thinking about using BooBoo but I need to target php7.

**Comment by mindplay-dk** [comment]
No release since over a year, what's the hold up? Is the project stalled?

I'd rather not depend on dev-master, as this tends to create dependency conflicts.

If you aren't ready to release due to stability concerns, e.g. not expecting any breaking changes prior to release, maybe you could create a `2.0` branch, so we can depend on `^2` with `minimum-stability` of `dev`?

**Comment by nikolaposa** [comment]
@mindplay-dk As for dependency conflicts when using `dev-master`, I think they can somewhat be mitigated by using `dev-master as 2.0.0` constraint.

**Comment by drealecs** [comment]
I'd like to push a bit on this again.
Can I do something to help? Is there any other things remaining to be done for 2.0?
Maybe you can create some github issues if you have some changes in mind and we can help with them.

**Comment by shrikeh** [comment]
I too would be interested in helping if maintainers are looking for a hand

**Comment by drealecs** [comment]
Hey @brandonsavage, from what I can see you're not really active here.
I might be a bit harsh even if I don't want to: can you pass the maintainer role to a person that could be more active?
I don't know how things work in @thephpleague but isn't someone that can take over?

Even if the projects are well written here and there, the lack of maintainability will only make them legacy code that less and less people will use.

**Comment by jblotus** [comment]
I agree with the idea that league packages should be actively maintained. I'm sure there are a few willing people to help?

**Comment by shrikeh** [comment]
I'd jump at the chance.

On 18 Jan 2017, at 15:36, James Fuller <notifications@github.com> wrote:

I agree with the idea that league packages should be actively maintained.
I'm sure there are a few willing people to help?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/thephpleague/booboo/issues/36#issuecomment-273508746>,
or mute the thread

**Comment by brandonsavage** [comment]
PHP 7 support is fully integrated into master and there are no "gotchas" in the code. Formal support will be in version 2.

**Comment by KorvinSzanto** [comment]
@brandonsavage Is there any timeline on Version 2? From what I can see this project looks abandoned :(
